import type { Weapon } from '../../../game/types';

export const WEAPONS: Record<string, Weapon> = {
  runeweave_carbine: {
    id: 'runeweave_carbine',
    name: 'Runeweave Carbine',
    flavor: 'An assault carbine inscribed with woven sigils; each round hums blue on discharge.',
    class: 'rifle',
    slot: 'primary',
    dmgMin: 4, dmgMax: 6,
    aim: 0, crit: 10,
    rangeShort: 7, rangeLong: 14,
    ammo: 4, apCost: 1,
    tag: 'runic',
  },
  hexbore_scattergun: {
    id: 'hexbore_scattergun',
    name: 'Hexbore Scattergun',
    flavor: 'Iron-bound shotgun fed with alchemical pellets that fragment on impact.',
    class: 'shotgun',
    slot: 'primary',
    dmgMin: 6, dmgMax: 9,
    aim: 10, crit: 10,
    rangeShort: 3, rangeLong: 7,
    ammo: 3, apCost: 1,
    tag: 'alchemical',
  },
  arclight_marksman: {
    id: 'arclight_marksman',
    name: 'Arclight Marksman',
    flavor: 'A precision longrifle that focuses a bolt of captured lightning down its length.',
    class: 'sniper',
    slot: 'primary',
    dmgMin: 7, dmgMax: 10,
    aim: -10, crit: 25,
    rangeShort: 12, rangeLong: 22,
    ammo: 2, apCost: 2,
    endsTurn: true,
    tag: 'runic',
  },
  whisperneedle_smg: {
    id: 'whisperneedle_smg',
    name: 'Whisperneedle SMG',
    flavor: 'Silenced by fae-sigils that drink the muzzle report; a hail of silvery needles.',
    class: 'smg',
    slot: 'primary',
    dmgMin: 2, dmgMax: 4,
    aim: 15, crit: 15,
    rangeShort: 5, rangeLong: 10,
    ammo: 6, apCost: 1,
    tag: 'fae',
  },
  dragonmaw_autocannon: {
    id: 'dragonmaw_autocannon',
    name: 'Dragonmaw Autocannon',
    flavor: 'A heavy crew-belt cannon; bolts glow orange and crack the air like distant roars.',
    class: 'heavy',
    slot: 'primary',
    dmgMin: 5, dmgMax: 8,
    aim: -5, crit: 10,
    rangeShort: 8, rangeLong: 16,
    ammo: 3, apCost: 1,
    tag: 'draconic',
  },
  sigilshot_pistol: {
    id: 'sigilshot_pistol',
    name: 'Sigilshot Pistol',
    flavor: 'A compact sidearm whose grip is etched with a focusing sigil.',
    class: 'pistol',
    slot: 'sidearm',
    dmgMin: 2, dmgMax: 4,
    aim: 10, crit: 5,
    rangeShort: 5, rangeLong: 10,
    ammo: 4, apCost: 1,
    tag: 'runic',
  },
  thornlock_revolver: {
    id: 'thornlock_revolver',
    name: 'Thornlock Revolver',
    flavor: 'A heavy wheel-gun chambered for thorn-cored rounds that bloom on impact.',
    class: 'pistol',
    slot: 'sidearm',
    dmgMin: 3, dmgMax: 5,
    aim: 0, crit: 15,
    rangeShort: 4, rangeLong: 8,
    ammo: 3, apCost: 1,
    tag: 'mundane',
  },
};

export const PRIMARY_WEAPONS = Object.values(WEAPONS).filter((w) => w.slot === 'primary');
export const SIDEARMS = Object.values(WEAPONS).filter((w) => w.slot === 'sidearm');
